CREATE OR REPLACE FUNCTION encode_base62(id BIGINT) RETURNS TEXT AS $$
DECLARE
    prime_multiplier BIGINT := 1123456789;
    prime_xor BIGINT := 9876543211;
    shuffled_id BIGINT;
    chars TEXT[] := ARRAY['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];
    result TEXT := '';
    remainder INT;
BEGIN
    IF id = 0 THEN
        RETURN '0';
    END IF;
    shuffled_id := (id * prime_multiplier) # prime_xor;
    WHILE shuffled_id > 0 LOOP
        remainder := shuffled_id % 62;
        result := chars[remainder + 1] || result;
        shuffled_id := shuffled_id / 62;
    END LOOP;
    RETURN result;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE TABLE urls (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    short_code TEXT GENERATED ALWAYS AS (encode_base62(id)) STORED UNIQUE,
    long_url TEXT NOT NULL,
    visit_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
